### PR TITLE
Multi-tenancy

### PR DESCRIPTION
**Pull request by mobinseven**
In this PR I suggest a multi-tenant structure with these specifications:

1.	Single Shared DB
2.	Each tenant can manage their own roles
3.	Single-Level (No sub-tenants)
4.	Single-tenant friendly (optional multitenancy) 
5.	Each user belongs to only one tenant at a time

I used a bookstore exhibition problem as example. 

Instructions:
After logging in as a “User” (in contrast with Admin), go to “Bookstore” page from nav menu.
You can already add/remove books (just as any other enitity. See specification 4). 

You can create you own bookstore from “My Bookstore”. After choosing a title for your bookstore (and maybe followed by some payment procedure in the real world) you will have your own bookstore (tenant). An initial role called “TenantManager” with all permissions, is created for your bookstore and assigned to you.

The “TenantManager” can define books of their own bookstore, manage their bookstore users and roles.

In “My Bookstore” tab you can see “Users” and “Roles” buttons. They will navigate you to our own “Admin/Users” and “Admin/Roles” pages, but with tenant specific data. You, as a “TenantManager”, can only see your bookstore (tenant) users. You can also invite existing users to your bookstore. And, of course, remove users from your tenant (like firing your employees!).

The inviting procedure, in the real world, is done, e.g. by an invitation link. But here we trivially add users forcefully. Once a user joined your bookstore (tenant), they can not join other bookstores (See specification 5).

You can define your own roles with different permissions, and assign them to your users (See specification 2).

Anonymous users can see all books and their corresponding bookstore (thanks to `IgnoreQueryFilters()`. See specification 1).

So as a test you can:
1.	Create user1
2.	As user1 create bookstore1 
3.	Create user2
4.	As user1 invite (add) user2 to bookstore1
5.	As user2 create book1
6.	Create user3
7.	As user3 create bookstore2 
8.	As user3 create book2
9.	As anon user you see book1 of bookstore1 and book2 of bookstore2.

**Caution**: This PR includes breaking changes to db. So, you may need to use a new db to test it out.

Some explanations:

1. Constants.cs containing Constants (renamed ProfileConstants.cs).
2. `UserSession` was not a reliable source of `TenantId` in my experience. Because we make many accesses to db before initialization of UserSession. I made `TenantId` a property of `ApplicationDbContext`.
3. The Root Tenant is the default tenant of this structure. All users belong to the root unless they join another tenant. **Thou shalt not rename the root tenant!** We rely on its title and this can be considered as a known issue.

Your comments, suggestions and **objections** are more than welcome!

Refrences:

- [Manage identity in multitenant applications](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/)
- #162 

Here is a schematic of the final structure:

OptionalMultitenancy

### CODE REVIEW

**Comment by GioviQ** [comment]
Every tenant should define a custom theme like in Orchard CMS.

**Comment by mobinseven** [comment]
> Every tenant should define a custom theme like in Orchard CMS.

Yes. Anything (including themes) can become an ITenant entity and get customized by each tenant.

**Comment by soomon** [comment]
> Every tenant should define a custom theme like in Orchard CMS.
What do you mean with theme? A custom branding? Like colours, logo etc?

**Comment by GioviQ** [comment]
> > Every tenant should define a custom theme like in Orchard CMS.
> 
> What do you mean with theme? A custom branding? Like colours, logo etc?

Yes a custom layout.

**Comment by justSteve** [comment]
Given that a Tenant is able to create his own store, does he have a way to invite normal users to that store?

That's the system I had to create in my last position -- we called them 'Affiliates'. Any promotional links they distributed needed to include ?idAff=[whatever]. Any sales that resulted from a session started with that query string would be credited with the given affiliate.

**Comment by soomon** [comment]
I was assuming a tenant is more aone company that has multiple workers assigned to the same account and not for affiliates, which do not require to work under 1 tenant

**Comment by GioviQ** [comment]
> I was assuming a tenant is more aone company that has multiple workers assigned to the same account and not for affiliates, which do not require to work under 1 tenant

It is better to use a general definition like https://en.wikipedia.org/wiki/Multitenancy

**Comment by mobinseven** [comment]
> Given that a Tenant is able to create his own store, does he have a way to invite normal users to that store?

Yes. From users management page.

**Comment by justSteve** [comment]
@soomon I think probably that's the initial intent -- Tenant == Department. But if one looks to tackle an ecomm application being able to handle affiliate sites would (imo) be a differentiator between 'one-off' (ad hoc) vs. something more enterprisie.

**Comment by enkodellc** [comment]
Thanks @mobinseven. I reviewed the code and it looks pretty solid. @DanielBunting, @ganmuru   can guys take a look and offer your opinion?  

I like the discussion. Please test it out and offer suggestions. This is going to be a great feature.

**Comment by mobinseven** [comment]
@enkodellc Thanks. Yes. A lot of discussion is needed. It is now ready for testing.

**Comment by GioviQ** [comment]
While searching for an EF core free design tool, I found nHydrate and this interesting article https://nhydrate.com/building-a-multi-tenant-application/

**Comment by justSteve** [comment]
In an earlier life I faced a *multi-tenant-per-db* problem that I expected
I would solve by defining a *tenant-per-schema* approach. e.g. instead of a
*dbo.MyUsers* table it would be *tenant1.MyUsers* and *tenant2.MyUsers *tables.
(i was only dealing with tens of dozens of tenants, not
hundreds/thousands.) At first glance, nHydrate would have been vastly
superior.

It seems nHydrate attacks the problem of multi-tenancy at the root and
would be an awesome addition. Would you consider it to be mature enough
tool?

**Comment by enkodellc** [comment]
@justSteve I am always open to discussions on these issues. I do want to avoid many third party libraries in most cases when something can be done without much complexity and maintenance. Just like everything there is a compromise to be made when it comes to items like this. I hope this discussion continues with additional contributors voicing their opinion. I am in my own silo still with existing client work and trying to keep up with the current BB PR's and of course the constant updates on Blazor / .net core.

**Comment by ganmuru** [comment]
There are multiple strategies (separate db for each tenant, one db with tenant id as one of the column,  or separate scehma per tenant etc. ) for multi-tenant architecture and whatever we choose it needs to support all those scenarios. I would suggest to look into FinBuckle : [https://www.finbuckle.com/MultiTenant/Docs/CoreConcepts ](url). This one can handle all those strategies. [https://www.finbuckle.com/MultiTenant/Docs/CoreConcepts#multitenant-strategies](url)

**Comment by ganmuru** [comment]
> @justSteve I am always open to discussions on these issues. I do want to avoid many third party libraries in most cases when something can be done without much complexity and maintenance. Just like everything there is a compromise to be made when it comes to items like this. I hope this discussion continues with additional contributors voicing their opinion. I am in my own silo still with existing client work and trying to keep up with the current BB PR's and of course the constant updates on Blazor / .net core.
> 
> @MarkStega , @ganmuru , @DanielBunting if you have a moment can I get your feedback on nHyrdate or @mobinseven's PR.
> 
> At this point I might rebase master with restructure and leave restructure available for the multi-Tenant functionality to be flushed out.

@enkodellc if this can hold for a week - I can review it later part of next week.

**Comment by GioviQ** [comment]
@justSteve  I found nHydrate because it is listed in https://docs.microsoft.com/en-US/ef/core/extensions/

It is an extension of Visual Studio and it uses just pure EF Core code.

**Comment by MarkStega** [comment]
I think that the PR looks reasonably solid. But to repeat something that I've said before, I don't think every possible feature needs to get implemented in BB. The risk is that it ends up so complex that few/no one can sort out what is going on and hence abandon trying to start with BB.

It's not perfect but I still suggest a core BB and then additional repositories that add various features. Multi tenancy is a good example as what is in this PR is a good approach, but not the only one. Ultimately I'd rather see the core BB and say 2 multitenant solutions with pros/cons of the implementations. I've also said before that things like data transfer between client & server need to follow one scheme in core BB, but then have satellite repositories that implement a REST API, another that does gRPC, etc.

So, again, this appears to be good work, I just question where it should land...

**Comment by soomon** [comment]
Doesn't it become even more complex if we have a core BB with 10 separate branches for different features?
Every change to core BB has to be replicated to all other branches and tested afterwards. Might branches  become incompatible to each other over time. And people will potentially ask how to combine a with b.
This might cause way more work than having 1 BB repo. 

But I see your point....
I don't have enough experience to determine what is actually better.

Whichever approach is chosen, I think we should try to keep things as decoupled as possible so they can be exchanged more easily. Everybody will benefit from that.

**Comment by MarkStega** [comment]
@soomon You are correct, there are issues either way. I know that in my 'real life' project I am maintaining both a REST API as well as gRPC and it is painful with lots of conditional compilation, etc. The best I can suggest is that for 'multi choice' implementations that a base class interface (as in iCommunicationAPI) be established and that each implementation build to be a NuGet package that you add into the base project rather than duplicating the base project. What this implies is that the interchangeable 'chunks' have to be really well architected and that interface definition is critically important.

**Comment by mobinseven** [comment]
> I don't think every possible feature needs to get implemented in BB. The risk is that it ends up so complex that few/no one can sort out what is going on and hence abandon trying to start with BB.

That's perfectly true. I cannot agree more. 

But the case of multi-tenancy is a rare one. I was seeking a multi-tenant solution for months and I couldn't find one. And as you can see it led me to design it myself. 

Furthermore, Multi-tenancy, in the rising tide of SaaS, is anticipated to become a **core** feature of every software package. From this point of view, in the accelerating age of cloud-ware technologies, it may even worth to reconsider the whole design based on those trends.

**Comment by soomon** [comment]
If we decide to separate things out, we should also commit to writing detailed manuals / providing examples so newbies (like me) and others have an easier time understanding the concepts of each part and how to implement it.
I agree with @mobinseven, multitenancy will be in high demand as SaaS is the future.

**Comment by AhLay** [comment]
hi guys, I apreciate the work done here and a big thanks to all of you. I would like to bring an idea into the discussion, why not designing the Multitenancy feature as a strategy, the USer can configure the strategy that is suitable to his senario or even implement his own strategy, doing so we can implement just the main stragegies (example: shared DB and a separate Tenant store).

**Comment by ganmuru** [comment]
> hi , I apreciate the work done here and a big thanks to all of you. I would like to bring an idea into the discussion, why not designing the Multitenancy feature as a strategy, the USer can configure the strategy that is suitable to his senario or even implement his own strategy, doing so we can implement just the main stragegies (example: shared DB and a separate Tenant store).

Finbuckle provides all the multi-tenant strategies. It would be better to have something like that integrated with the existing framework.

**Comment by mobinseven** [comment]
I started trying to implement BB multitenancy using @ganmuru  suggestion, [Finbuckle.MultiTenant](https://github.com/Finbuckle/Finbuckle.MultiTenant) . Soon, I will be back with updates on this.

**Comment by enkodellc** [comment]
@mobinseven I have not mentioned it yet but the new branch for dev is "development" I have kept "restructure" open since it had your other PR in it.  So please test / implement with that branch.

**Comment by mobinseven** [comment]
> @mobinseven I have not mentioned it yet but the new branch for dev is "development" I have kept "restructure" open since it had your other PR in it. So please test / implement with that branch.

@enkodellc Ok, thanks.

**Pull request closed without merging**
