### PR TITLE
Update APIResponseRequestLoggingMiddleware.cs

### PR DESCRIPTION
**Pull request by PatronizeKh**
add this code to finally scope 
httpContext.Response.ContentLength = responseBody.Length;

### CODE REVIEW

**Comment by GioviQ** [comment]
@PatronizeKh I have in the log

System.InvalidOperationException: The response headers cannot be modified because the response has already started.

**Comment by PatronizeKh** [comment]
@GioviQ didn't face this exception... 

move this line of code : httpContext.Response.ContentLength = responseBody.Length; 
just before stopWatch.Stop();

https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.Server/Middleware/APIResponseRequestLoggingMiddleware.cs#L89

**Comment by GioviQ** [comment]
it works now (it happend navigating to admin pages).

**Comment by PatronizeKh** [comment]
@GioviQ Perfect

**Pull request merged**
