### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by GioviQ**
Cookies requires SameSite attribute. See https://web.dev/samesite-cookies-explained/

Debugging with http, Chrome 80 does not accept SameSite=None. With https it is OK.

Other browsers may behave differently.

### CODE REVIEW

**Comment by GioviQ** [comment]
What about async without await?

**Comment by enkodellc** [comment]
Thanks @GioviQ for contributing and using Blazor Boilerplate. I will not be able to review / test at this moment. 

Please give more detail on the question: 

> What about async without await?

**Comment by enkodellc** [comment]
@GioviQ  is this PR ready? I am looking to merge all PR's today.

**Comment by GioviQ** [comment]
> @GioviQ is this PR ready? I am looking to merge all PR's today.

Yes if you agree.

**Comment by enkodellc** [comment]
I have most of this building on the restructure branch. Thanks for the refactor / deep dive.

My chrome is finally working!  I got an error so I am going to review and test a bit more but this is definitely a great PR.  I think it will get merged to both master and restructure today.

**Comment by enkodellc** [comment]
@GioviQ I pushed the changes to the restructure branch.
Everything looke pretty good except I ran into issues with the async / await in the Stores at runtime:  TodoStore, UserProfielStore, ApiLogStore

These errord out when running.

https://github.com/enkodellc/blazorboilerplate/blob/1ed5a39e34e232119adc5e4df3d6d8b5152b185b/src/BlazorBoilerplate.Storage/Stores/ToDoStore.cs#L46

If you want to you can review and submit a PR against this Branch. Thanks so much for your contributions!

I recommend you jump on the gitter chat: https://gitter.im/blazorboilerplate/community

**Comment by enkodellc** [comment]
I will test the PR against master now and merge if everything runs fine.

**Comment by GioviQ** [comment]
> @GioviQ I pushed the changes to the restructure branch.
> Everything looke pretty good except I ran into issues with the async / await in the Stores at runtime: TodoStore, UserProfielStore, ApiLogStore
> 
> These errord out when running.
> 
> https://github.com/enkodellc/blazorboilerplate/blob/1ed5a39e34e232119adc5e4df3d6d8b5152b185b/src/BlazorBoilerplate.Storage/Stores/ToDoStore.cs#L46
> 
> If you want to you can review and submit a PR against this Branch. Thanks so much for your contributions!
> 
> I recommend you jump on the gitter chat: https://gitter.im/blazorboilerplate/community

I experience no issue with async await. See https://github.com/enkodellc/blazorboilerplate/pull/209

**Pull request merged**
