### PR TITLE
Fixes #81 - updated to the stable dotnet core 3.1

### LINKED ISSUE #81: Upgrade to ASP. NET Core 3.1
Check https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/
And https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio
For release notes and migration information

Notes: even tough 3.1 has shipped, client side Blazor is still in preview, keep that in mind when upgrading nuggets.

### PR DESCRIPTION
**Pull request by acid12**
Additionally tried to update Blazor.Client related libs to newest preview version, but the app looked ... bad. There were errors about matblazor not being properly set.
It might be related to increment the version of Client project to netstandard2.1 (required with new libs) and matblazor being older version. Nevertheless it did not work, so the only changes here are working ones - upgraded to stable versions where applicable

### CODE REVIEW

**Comment by enkodellc** [comment]
Did you want to also update the azure pipelines for the .net core version 3.1?

**Comment by enkodellc** [comment]
I just updated my VS and installed .net core 3.1... keep getting the following error:  
Unable to find package Microsoft.AspNetCore.Blazor.Server with version (>= 3.1.0)

My Nuget update is suggesting the next preview version: 3.1.0-preview4.19579.2. 

I am holding off on this PR for a bit. Would rather have both client and server side in sync and MatBlazor updates all in one shot.

**Comment by acid12** [comment]
Uncheck the include prerelease version in nuget viewer.
Sure, let's wait for MatBlazor and update all together

**Comment by acid12** [comment]
@enkodellc I don't think I have access to configure the pipelines anymore, would need to double check.

**Pull request closed without merging**
