### PR TITLE
initial dual mode setup (incomplete)

### PR DESCRIPTION
**Pull request by witoldlitwin**
The code below IS NOT WORKING.
I tried implementing server side according to the Dual Mode example, bu I run into a dependency issue between AuthenticationStateProvider and HttpClient.
I attempted the workaround found here: https://github.com/aspnet/AspNetCore/issues/11867 but the code still throws me the following exception:
'Unable to resolve service for type 'System.Net.Http.HttpClient' while attempting to activate 'BlazorBoilerplate.Client.Services.Implementations.AuthorizeApi'.'

Maybe you'll be able to fix what I started.

### CODE REVIEW

**Comment by npraskins** [comment]
To use http client in serverside you need services.AddHttpContextAccessor() in Startup.cs then in the page where you were using the httpcontext, add @inject IHttpContext Accessor {namehere}

**Comment by enkodellc** [comment]
I will merge this into a new branch called dual.

**Comment by enkodellc** [comment]
@npraskins  if you wish you can now do a PR on the "dual" branch to update or @witoldlitwin  you can take his advice. Thanks to both of you for your help!

**Comment by enkodellc** [comment]
@NPadrutt  If you want to take a look at this PR / Branch and offer any input it would be greatly appreciated as well.

**Comment by NPadrutt** [comment]
@enkodellc I oriented myself on this project https://github.com/Suchiman/BlazorDualMode

As far as I can see the regarding code is already in the startup, but commented out:

```
// Server Side Blazor doesn't register HttpClient by default
            if (!services.Any(x => x.ServiceType == typeof(HttpClient)))
            {
                // Setup HttpClient for server side in a client side compatible fashion
                services.AddScoped<HttpClient>(s =>
                {
                    // Creating the URI helper needs to wait until the JS Runtime is initialized, so defer it.      
                    var uriHelper = s.GetRequiredService<NavigationManager>();
                    return new HttpClient
                    {
                        BaseAddress = new Uri(uriHelper.BaseUri)
                    };
                });
            }
```

This worked for me so far. My issue then was with the authentication, which didn't work on Server Side.

**Comment by NPadrutt** [comment]
mh, maybe I overlooked it, but I guess this is missing:

`
services.AddMvc().AddNewtonsoftJson();
`

**Pull request merged**
