### PR TITLE
Add ApiContent as BackgroundService task

### PR DESCRIPTION
**Pull request by charlierlee**
It would be nice if this template could pull data from an api server side and store it in a database. In this case it is pulling a simple page from Wikipedia.

### CODE REVIEW

**Comment by GioviQ** [comment]
It is not a general purpose feature. Retrieving wiki pages and saving in db is too specific.
When a developer clones this repository it is very probable that he wont't use this feature.

**Comment by GioviQ** [comment]
If you have time, I could suggest a useful way to add a BackgroundService to this repository...

**Comment by charlierlee** [comment]
I 100% agree. Thanks for your feedback. I will close this out.

**Comment by charlierlee** [comment]
> If you have time, I could suggest a useful way to add a BackgroundService to this repository... (because I like how you code)

That would be great. Thanks.

**Comment by GioviQ** [comment]
Account confirmation by email is so important that the method https://github.com/enkodellc/blazorboilerplate/blob/master/src/Server/BlazorBoilerplate.Server/Managers/EmailManager.cs#L137 is not enough.
I was thinking about an QueueEmailAsync method which stores email in a new Emails db table and a background service sending emails with SendEmailAsync.
So when the SMTP server configuration is wrong or the server is not working, the service can retry sending the emails.
Also we can keep track of sent emails.

The email message has so many fields that maybe it is the case to serialize it as json and store so in Emails table.
What do you think about it?

**Comment by charlierlee** [comment]
I like it. Is it ok if I wait a up to a week or two before starting it? Once I get started it won't take me long. Let me know if you have any changes in the mean time, or if you decided to take it on yourself.

**Pull request closed without merging**
