### PR TITLE
Fixes #42 - Add Google External Auth provider

### LINKED ISSUE #42: IS4 - Sign-in with External Identity Providers - New Feature
Looking for someone to submit a PR for external authentication like Google / Twitter on the IS4 branch.
 
 http://docs.identityserver.io/en/latest/topics/signin_external_providers.html

### PR DESCRIPTION
**Pull request by acid12**

### CODE REVIEW

**Comment by acid12** [comment]
PR for issue #42

**Comment by acid12** [comment]
Closing #42 when merged

**Comment by enkodellc** [comment]
Ha, just when I got your code merged and I want to sign up with google to get my API key I get an error from Google: **Couldn't initialize warning A network error occurred and the request could not be completed.**  I will try later.

**Comment by enkodellc** [comment]
Well I got it running locally and tested quite a bit. Then I went to publish to test live and I got an error:
**Assets file 'E:\Websites\BlazorBoilerplate\src\BlazorBoilerplate.Server\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.0'**

Which led me here:
https://github.com/aspnet/AspNetKatana/issues/251
https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0

I am done for the night, Might try and submit a PR for your PR...

**Comment by enkodellc** [comment]
@acid12  I merged some changes.  Everything looked pretty solid.

- I noticed that some of my test google users had issues with invalid username's because it was using my Google First Name and Last Name with a space in it so I needed to do some additional changes for those test cases.
- I do like separating out some of the startup functionality. It was easier for this PR to keep it together for the merge. Let's do that in a separate PR? 
- I agree we would not need the Confirm Email for External Auth. 
- I could not publish still but will try a few different things today. Did you try publishing your PR?
- I wanted to publish so I could create my own Google API and test on my demo  / live site to see if I could get rid of the success page and make some changes to the error page.

Hopefully I can get it to publish as we have both have time into this PR and I think it is a good example. Maybe if we cannot we do Twitter Login instead of Google.

**Comment by enkodellc** [comment]
Well I was able to get it published but then got an "undefined 'map'" javascript error after putting on the server. Will continue to debug.

**Pull request merged**
