### PR TITLE
SSB auth cookies

### PR DESCRIPTION
**Pull request by marcotana**
Passed the auth cookies received from IdentityServer to/from browser and server to resolve browser refreshes that lose auth information.

### CODE REVIEW

**Comment by enkodellc** [comment]
@marcotana - First off thanks for the PR. I ALWAYS have a terrible time when debugging both CSB and SSB / switching. This time is no exception. Both are bombing. Please confirm they working for you. Test specifically the 

1. Login in then click refresh.
2. Forum / Chat.

I am going to retest from my master to make sure everything is working from the update last night.

@Oleg26Dev can you please test this as a fix for #139 as well. Thanks

**Comment by rc-marcotana** [comment]
Just tested my fork and the SSB worked just fine.  THE CSB also worked as you described above with the forum data showing when I switched and vice-versa.  The only thing that didn't work for me is the Logout on CSB but worked on SSB.  I will investigate that piece but I'm not sure if that's an issue before.

**Comment by enkodellc** [comment]
I uploaded your changes to the demo site and it fails. Might not be from your changes but I cannot get it to work for the life of me. So frustrated with Blazor at the moment. I am walking away from it for today. I will try again on Saturday. Maybe some others can test.

**Comment by mobinseven** [comment]
As I **randomly** got this exception:
`System.InvalidOperationException: 'The given header was not found.'
`
in Logging out (Logout() in AthorizeApi.cs) operation, and I don't know why, I suggest this change:
```
            List<string> cookies = null;
            if (_httpClient.DefaultRequestHeaders.TryGetValues("Cookie", out IEnumerable<string> cookieEntries))
                cookies = cookieEntries.ToList();
```

**Comment by enkodellc** [comment]
@mobinseven I just pushed your suggested changes. Thanks

**Comment by mobinseven** [comment]
Another issue about this issue which caused iOS Safari & Chrome problem:
I found that `_http.HttpContext` in App.razor returned null once while starting the app. So:
```
        if (_http != null && _http.HttpContext != null && _http.HttpContext.Request.Cookies.Any())
        {
           ...
        }
```

**Pull request merged**
