### PR TITLE
Ecommerce

### PR DESCRIPTION
**Pull request by mdora7**
ecommerce integration

### CODE REVIEW

**Comment by enkodellc** [comment]
@GioviQ  I asked @mdora7  to create this PR. If you have time please give him feedback. I will do the same. I am running into so dev issues with my machine at the moment since I just changed several pieces of hardware.

**Comment by enkodellc** [comment]
@mdora7 the first thing I see is that the Migration is broken. It does not create the table Categories and you removed the rest of the tables. I am resolving and will submit an updated PR to your branch.

**Comment by mdora7** [comment]
Sorry at that moment I've lived a bug with EF Core.
if you want I quickly fix it. You don't bother. But if it's already ok, I
am waiting

Keith ***@***.***>, 6 Eyl 2021 Pzt, 13:00 tarihinde şunu
yazdı:

**Comment by enkodellc** [comment]
I am working on it. First had to fix something in the master branch. VS is causing several issues for me.

**Comment by enkodellc** [comment]
I will merge and then  submit some changes to get it closer.  I have it working now but still several areas of improvement could be done. Thanks for the effort so far @mdora7

**Comment by mdora7** [comment]
As you know I will go on. This PR was just for review by yourself.
The next PR will be clear than the previous, thank you.

Keith ***@***.***>, 7 Eyl 2021 Sal, 07:30 tarihinde şunu
yazdı:

**Comment by enkodellc** [comment]
@mdora7, great. Please checkout my changes and move forward. Thanks!  I will also add more to the readme and notes for you before we merge with master.

**Pull request merged**
