### PR TITLE
Postgres DB support

### PR DESCRIPTION
**Pull request by vd3d**
Support of Postgres DB

### CODE REVIEW

**Comment by acid12** [comment]
@vd3d correct me please if I'm wrong, but from the changes it seems like you removed support for SqlServer and replaced it purely with PostgreSql?

I'd think we'd like to support both platforms.

**Comment by enkodellc** [comment]
@vd3d i agree with @acid12. I am thinking we can create a branch for postgres. I am open to other suggestions though.

**Comment by acid12** [comment]
Ef core supports migrations with multiple providers, this is the direction we should follow.

https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli

**Comment by vd3d** [comment]
> @vd3d correct me please if I'm wrong, but from the changes it seems like you removed support for SqlServer and replaced it purely with PostgreSql?
> 
> I'd think we'd like to support both platforms.

Not at all... it support postgress, it is only an addition

**Pull request merged**
