### PR TITLE
add Terraform config

### PR DESCRIPTION
**Pull request by charlierlee**
instructions to deploy blazorboilerplate into aws. I will point out that running sql requires at least 2 Gb of RAM on the host. To get around that I added a paging file, and used this version of sql server: https://github.com/justin2004/mssql_server_tiny

### CODE REVIEW

**Comment by GioviQ** [comment]
Does it work on Azure too?

**Comment by charlierlee** [comment]
> Does it work on Azure too?

I would create a folder called AWS, and a folder called Azure, etc, and have each terrahash specific deployment defined in each folder. You could add more than just AWS and Azure. Terraform supports a large list of hosting providers. This commit would be a good place to start.

**Comment by GioviQ** [comment]
I like your work, but I don't know Terraform, so instead of a Readme.md can you PR a doc page in https://github.com/enkodellc/blazorboilerplate/tree/master/docs?

**Comment by charlierlee** [comment]
@GioviQ This is how I learned it: https://www.youtube.com/watch?v=SLB_c_ayRMo. Once you learn how to use the tool, then the code becomes documentation. So not sure how helpful I can be here.

**Comment by GioviQ** [comment]
Good! https://blazor-boilerplate.readthedocs.io/en/latest/quickstarts/deploy_with_terraform.html

**Pull request merged**
