### PR TITLE
only use StoreName.My in Linux

### PR DESCRIPTION
**Pull request by charlierlee**
Need to update doc to correlate with code change. We need to conform to the standards of what .net supports. See https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography and lookup CurrentUser\My vs LocalMachine\My. Nowhere is there "WebHosting".

We should also allow user secrets. See https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-5.0

### CODE REVIEW

**Comment by enkodellc** [comment]
@charlierlee   It is recommended to be "WebHosting" folder. So I would suggest a PR Reverting the code back to "WebHosting" versus "My".  This should have not changed as it would have broken other solutions.

https://stackoverflow.com/questions/26681192/whats-the-difference-between-the-personal-and-web-hosting-certificate-store

**Comment by GioviQ** [comment]
"My" certificate store is not the proper location to put certificate on Windows Server, because "My" is the current user and for security IIS application pool has special user to run web processes.
So "My" could be suitable for Linux but not for Windows Server.
"Web hosting" is the proper location to put certificates on Windows Server like https://www.win-acme.com/ does.
Please corret your linux specific updates.

**Comment by charlierlee** [comment]
"WebHosting" is not supported in Linux in any way. It either works the way I proposed or it doesn't work in Linux at all.

Feb 6, 2021, 11:41 by notifications@github.com:

**Comment by charlierlee** [comment]
I could have it use WebHosting for Windows and My for Linux if that is ok.

Feb 6, 2021, 11:41 by notifications@github.com:

**Comment by GioviQ** [comment]
just for info https://stackoverflow.com/questions/26681192/whats-the-difference-between-the-personal-and-web-hosting-certificate-store

**Comment by enkodellc** [comment]
@GioviQ  thanks for posting on this. I don't like the idea changing from "WebHosting" as it would break existing repos. Thanks @charlierlee for the PR's!

**Comment by GioviQ** [comment]
> @GioviQ thanks for posting on this. I don't like the idea changing from "WebHosting" as it would break existing repos. Thanks @charlierlee for the PR's!

"WebHosting" is the same as before now for Windows.

**Pull request merged**
