### PR TITLE
Multitenancy

### PR DESCRIPTION
**Pull request by mobinseven**
First Part: Server
In this pull request I suggest a multi manager structure. Where each manager(tenant Owner) manages a unique department(tenant) with its own employees(tenant claim owners). Each department data should not be visible to others. 

business structure

Managers create tenants and add users to them - by giving them a claim named "tenantid" and a value equal to that tenant Id.

tenant flowchart

### CODE REVIEW

**Comment by enkodellc** [comment]
Looks good so far. This is really great work.Love the images. They will help out tremendously on a wiki.

I am just not sure if we should have this in the master branch, or try to move it to the "restructure" branch. @DanielBunting  what do you think?

**Comment by mobinseven** [comment]
> Looks good so far. This is really great work.Love the images. They will help out tremendously on a wiki.

Glad to hear that. 

> I am just not sure if we should have this in the master branch, or try to move it to the "restructure" branch. 

This is just what obsessed my mind too. I would love to migrate changes to restructure branch if you say so. Otherwise we can wait to restructure branch merge with master and then move on toward this branch (which seems more logical to me).

**Comment by enkodellc** [comment]
Let's hear from Daniel. If he doesn't want to influence his progress then we will merge it into the next release of the current master. The only issue will then be the time to merge it into restructure... might be less work to move into restructure now than later but just not released as quickly. Restructure branch is actually moving along well and I think could be released fairly soon. I don't want to get in the way of progress so my goal is to see what you very kind contributors want to do.

**Comment by enkodellc** [comment]
@mobinseven where you successful in adding the ITenent Interface to the ApplicationUser model? I have converted your PR to the restructure branch but I am running into many issues. Maybe my implementation is wrong. I spent a lot of time today on it and I might just push it to another branch for others to review since I need to move on and merge other PR's.

**Comment by mobinseven** [comment]
I am still working on this branch. But it is almost ready. I will start committing and documenting the changes in upcoming days.
But since you've brought up this, according to [this](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/#identity-in-a-multitenant-app) comprehensive and useful series of articles, roles should be managed by tenants. So what I will do is to make an `ApplicationRole : ITenant` to bring roles into tenants entities. Each organization can have their own roles and assign them to users.

**Comment by soomon** [comment]
boy this will be a huge improvement for all of us. Thanks for investing so much of your time!

**Comment by enkodellc** [comment]
@mobinseven I have most of this PR ready to merge into restructure branch. I need to test a bit more. Do you want me to push my changes and then you can submit a PR against the restructure branch?

**Comment by mobinseven** [comment]
@soomon I'm pleased to hear that. I hope you like the outcome too.

@enkodellc The changes mentioned above are a little bit breaking! So if we put them at the end of the queue that would be better.

**Pull request closed without merging**
