### PR TITLE
added SCSS support module.

### PR DESCRIPTION
**Pull request by michaelrinderle**
**REQUEST**

Request adds SCSS support to project. 

The project is stored in the Modules folder under : 

BlazorBoilerplate.Theme.Scss

**PROJECT IMPACT**

Vanilla CSS users can continue on with the compiled site.css file as usual. Sass users will be able to modify the current project SCSS from the project folder and recompile the files to the site.css file located in the Theme.Material project folder to render styles. 

**REQUIREMENT**

Sass users will need [WebCompiler ](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.WebCompiler)in VS to utilize the feature.

### CODE REVIEW

**Comment by GioviQ** [comment]
I don't like the idea to have a new project only for css.
@enkodellc what do you think about it?

**Comment by charlierlee** [comment]
I don't use visual studio when working with this project. I use vscode, and would not have access to VS extensions. <-- My 2 cents

**Comment by michaelrinderle** [comment]
> I don't like the idea to have a new project only for css.
> @enkodellc what do you think about it?

I agree. I converted the interop.js and background-worker.js to Typescript, then combined with my sass files in a project under modules.  I just didn't want to screw up your namespaces so I separated it and didn't know if anyone was interested in adding TS to the project. 

> I don't use visual studio when working with this project. I use vscode, and would not have access to VS extensions. <-- My 2 cents

I added the webcompiler nuget package with the project. It should hook into the dotnet build to compile assets from the docs.

**Comment by GioviQ** [comment]
Css reorganization should go to me in this direction:
https://maintainablecss.com/chapters/semantics/
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-5.0

**Comment by enkodellc** [comment]
I agree with Gio, using the css/ scss isolation as much as possible.  With the css /sass at the component level then when / if you add more theme modules you could update it accordingly. Is that correct Gio? It would be a step on the right direction.  @michaelrinderle do you want to take on that project?

**Comment by michaelrinderle** [comment]
Sure. I could tackle that. Couple questions for now.

- Preferred Location for the web compiler nuget and compilerconfig.json file?
- Stick to the docs recommendation with sass support or move to separate location? 

Docs recommend the following convention for regular css isolation:

Example.razor        # component
Example.razor.cs     # <- if codebehind is used
Example.razor.css   # isolated css
Example.razor.sass # <- if Sass is support

**Comment by GioviQ** [comment]
To read also https://github.com/madskristensen/WebCompiler/issues/468

**Comment by michaelrinderle** [comment]
Users over there recommended Gulp (I thought people were asking if that was dead for have a decade now), which would mean introducing Node into the project to facilitate the compilations. :/

**Comment by charlierlee** [comment]
Check my pull request. I think I got it!

**Comment by michaelrinderle** [comment]
i browsed webcompiler's code and it actually just wraps node too. people debate if projects are dead all the time but what really matters is if it works. for fairly vanilla sass it works fine. It's just one nuget package and a config files for sass. It also is compatible with blazor's css isolation model out of the box since blazor restricts the *.razor.css file to the components file directory to be picked up during the build process to make the isolation tags. 

if you want to go this route, its fairly straightforward. 

1. Grab BuildWebCompiler [1.12.405] nuget package for your demo/admin module.

2. Drop a compilerconfig.json file in each module. 

3. Right click on your .scss file to compile if you have the vs2019 extension to add it to the config file or update your config file manually in vscode. 

`[
  {
    "outputFile": "Shared/Components/footer.razor.css",
    "inputFile": "Shared/Components/footer.razor.scss"
  }
]`

4. Drop an app.scss in your demo root for global  settings so you can import in your components scss. 

`@import '../../app.scss';

@mixin shadow {
    color: #a9a9a9;
    font-size: .75em;
    text-shadow: 2px 1px 1px $footer-bg-color;
}
`
5. vs2019 folds like no other, the component, code behind, css, min css, and sass. It's a delight. I hope you got this in code. 

footer

Do what you will with this. I gotta move on.

**Pull request closed without merging**
