### PR TITLE
Dev pwa

### PR DESCRIPTION
**Pull request by np-at**
Basic PWA functionality working.  In order to install you must be using a chromium based browser.
If we're serious about implementing BBP as a PWA then someone should really go through and rethink some of the functionality implementation (most of it is dependent on an active connection to the server)

This is still very much a work in progress but the foundation is there....

also I disabled the automatic browser launch on run as it makes dealing with service-worker caching a pain

#192 - Take a look

### CODE REVIEW

**Comment by np-at** [comment]
I can't seem to replicate this build error... 
Anyone know what's happening with the pipeline job?

**Comment by np-at** [comment]
It looks like the pipeline is still using docker sdk version 3.1.101, maybe that's causing the IL linker issue?

**Comment by np-at** [comment]
Although this technically works as a PWA I'm not sure that it should be merged into the main branch as most of the services were not designed with being a PWA in mind.  Maybe it should go into its own branch for now?

**Comment by enkodellc** [comment]
@np-at  Thanks. Looks like there is very little conflicting with our latest changes. 

Just to keep you updated I have a few more changes for restructure before I dive into this more. If you want / need to commit more to the PR feel free to do so.

**Comment by GioviQ** [comment]
@np-at Please test pwa on development branch Debug_CSB where I made some test about it.

**Pull request closed without merging**
