### PR TITLE
Adds LiveReload to Server and Client side blazor.

### PR DESCRIPTION
**Pull request by Kronos11**
Currently works best using 
`dotnet run watch -c Debug_CSB` for client side and 
`dotnet run watch -c Debug_SSB` for server side.
IIS does work most of the time if using `Ctrl+F5` sometimes you may need to re-build manually.

### CODE REVIEW

**Comment by enkodellc** [comment]
Code looks great, will test tonight! Thanks so much for contributing!

**Comment by enkodellc** [comment]
@Kronos11 It seemed to work for me SSB but on CSB I am getting an error. Got to love Blazor. I will try and reboot and possibly rebuild the project.

**Comment by enkodellc** [comment]
I got it to work on CSB.. well sort of I used `dotnet run watch -c Debug_CSB`  and then went to todo list and edited the title and clicked save. The site reloaded but the title did not update the title.

It did this on both Chrome and FF.  Since I do most of my dev on CSB. Please give your feedback on this package. Right now I am leaning towards it not being ready for Blazor CSB.

**Comment by enkodellc** [comment]
@Kronos11  Did you read this?
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/?
**Auto-rebuild in Visual Studio**

@GioviQ is creating a PR for it. He is fast so I think by tomorrow we will be testing!  Update your VS to 16.6

**Comment by Kronos11** [comment]
This is great news, I think we should do this instead of my PR

**Comment by Kronos11** [comment]
Closing due to: latest blazor preview which adds this.

**Pull request closed without merging**
