### PR TITLE
Use Copy instead of Exec (works on linux)

### PR DESCRIPTION
**Pull request by charlierlee**
I am not using Windows, and I was able to get it working on Linux. I have a sequence of changes I would like to make. This pull request seems like a good place to start.

### CODE REVIEW

**Review by GioviQ — CHANGES_REQUESTED** [review]
It should be better to use https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem.iswindows?view=net-5.0#System_OperatingSystem_IsWindows to detect OS regarding specific features.

**Comment by charlierlee** [comment]
Unless the code works in both cases of course.

**Comment by GioviQ** [comment]
> Unless the code works in both cases of course.

Of course, I am talking about cert store.

**Comment by charlierlee** [comment]
Ok. I will make the change. Thanks

**Comment by GioviQ** [comment]
> Ok. I will make the change. Thanks

Consider also that https://github.com/enkodellc/blazorboilerplate/blob/master/src/Server/BlazorBoilerplate.Server/Startup.cs#L208 is windows specific, because it takes certificate for Identity Server from Cert store.

**Comment by charlierlee** [comment]
alternatively, I would be happy to revert the cert store change for now until we get this pull request complete. Then I can work on building an azure based hosting environment later.

**Review by GioviQ — CHANGES_REQUESTED** [review]
Please read this https://github.com/dotnet/runtime/issues/27658

**Comment by charlierlee** [comment]
Here is the documentation I am using to configure my linux cert store:

https://stackoverflow.com/questions/58763985/authenticate-to-azure-with-certificate-from-linux
#create certs
openssl req -new -x509 -newkey rsa:2048 -keyout localhost.key -out localhost.cer -days 365 -subj /CN=localhost

#create pfx
openssl pkcs12 -export -out localhost.pfx -inkey localhost.key -in localhost.cer

#add cert to store
#https://github.com/gsoft-inc/dotnet-certificate-tool

dotnet tool install --global dotnet-certificate-tool
certificate-tool add --file ./localhost.pfx --password "YOUR_PASSWORD" --store-name "My" --store-location "CurrentUser"

#show fingerpint
openssl pkcs12 -in ./localhost.pfx -nodes | openssl x509 -noout -fingerprint

**Review by GioviQ — APPROVED** [review]

**Pull request merged**
